[tools]
just = "1.52.0"
rust = { version = "stable", components = "clippy,rustfmt,llvm-tools-preview" }
pre-commit = "latest"
node = "26.2.0"
"npm:markdownlint-cli2" = "latest"
"npm:vite-plus" = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"aqua:EmbarkStudios/cargo-deny" = "latest"
"aqua:taiki-e/cargo-llvm-cov" = "latest"

[env]
TERM = 'xterm-256color'
