[tools]
just = "1.56.0"
rust = { version = "stable", components = "clippy,rustfmt,llvm-tools" }
pre-commit = "4.6.0"
node = "26.2.0"
"npm:markdownlint-cli2" = "0.22.1"
"npm:vite-plus" = "0.1.24"
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.137"
"aqua:EmbarkStudios/cargo-deny" = "0.19.9"
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"

[env]
TERM = 'xterm-256color'
